### PR TITLE
Add rate limiting to client

### PR DESCRIPTION
**Pull request by sandalwing**
@jyap808 this will help ensure API requests are kept approximately under requested amount

Signed-off-by: Xavier Sandal <sandalwing@sandalwing.com>

### CODE REVIEW

**Comment by sandalwing** [comment]
Hm, I actually see a few issues with my logic here.  I think I need some rest 😆 But I will continue to work on it

**Comment by jyap808** [comment]
Thanks, I will check it out after you revisit it.

**Comment by sandalwing** [comment]
Ah OK.  Revisiting with fresh eyes I think this is good actually (I got the idea from https://github.com/golang/go/wiki/RateLimiting).

If you look at the source from https://golang.org/src/time/tick.go?s=706:740#L11 for `NewTicker`, it will create a channel with buffer size of 1, so that the first read on `throttle` happens immediately, and if another read happens <200ms _after_ that, it will block until the interval is up, but otherwise let the read proceed.  WDYT?

**Comment by jyap808** [comment]
@sandalwing are you using this right now? Any issues with it?

**Comment by sandalwing** [comment]
It LGTM in my testing.  Feel free to CC me on issue if any bugs come up

**Pull request merged**
